name: utueji
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Service Locator
  get_it: ^8.0.3

  # Network
  dio: ^5.8.0+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  logger: ^2.3.0

  # UI & Utilities
  cupertino_icons: ^1.0.8
  form_builder_extra_fields: ^12.0.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.2.0
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  google_nav_bar: ^5.0.7
  uicons: ^1.0.1
  chatview: ^2.5.0
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.12.3
  chat_bubbles: ^1.7.0
  photo_view: ^0.15.0
  animate_do: ^4.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  fluttertoast: ^8.2.12
  custom_navigation_bar: ^0.8.2
  table_calendar: ^3.2.0
  reorderable_tabbar: ^1.0.6
  contained_tab_bar_view: ^0.8.0
  dashed_circular_progress_bar: ^0.0.6
  easy_date_timeline: ^2.0.9
  flutter_timeline_calendar: ^1.0.9
  flutter_easyloading: ^3.0.5
  toastification: ^3.0.3
  flutter_secure_storage: ^9.2.4
  get: ^4.7.2
  animations: ^2.0.11
  simple_circular_progress_bar: ^1.0.2
  font_awesome_flutter: ^10.8.0
  phone_form_field: ^10.0.8
  animated_bottom_navigation_bar: ^1.4.0
  carousel_slider: ^5.1.1
  flutter_rounded_progress_bar: ^0.3.2
  firebase_pagination: ^4.1.0
  flutter_animation_progress_bar: ^2.3.1
  timeago: ^3.7.1
  supabase_flutter: ^2.9.1
  dartz: ^0.10.1
  flutter_carousel_widget: ^3.1.0
  infinite_carousel: ^1.1.1
  banner_carousel: ^1.2.1
  carousel_slider_plus: ^7.1.1
  dotted_dashed_line: ^0.0.3
  skeletonizer: ^2.0.1
  shimmer: ^3.0.0
  flutter_dotenv: ^5.2.1
  parallax_animation: ^0.0.3
  flutter_tilt: ^3.2.1
  tab_container: ^3.5.3
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  roundcheckbox: ^2.0.5
  flutter_cached_pdfview: ^0.4.3
  internet_connection_checker_plus: ^2.7.2
  bottom_sheet: ^4.0.4
  syncfusion_flutter_charts: ^30.1.37
  social_sharing_plus: ^1.2.3
  share_plus: ^11.0.0
  rounded_loading_button_plus: ^3.0.1
  floating_action_bubble: ^1.1.4
  easy_stepper: ^0.8.5+1
  group_button: ^5.3.4
  dropdown_search: ^6.0.2
  form_builder_file_picker: ^5.0.0
  video_player: ^2.10.0
  google_places_flutter: ^2.1.0
  awesome_place_search: ^2.1.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  speech_to_text: ^7.1.0
  http: ^1.4.0
  appinio_social_share: ^0.3.2
  webview_flutter: ^4.13.0
  flutter_local_notifications: ^19.3.0
  form_builder_phone_field: ^3.0.0
  google_places_autocomplete_text_field: ^1.1.0
  sliver_snap: ^2.1.1
  buttons_tabbar: ^1.3.15

  # Firebase
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  google_sign_in: ^7.1.0
  cloud_firestore: ^5.6.10
  firebase_storage: ^12.4.8
  firebase_in_app_messaging: ^0.8.1+8
  firebase_messaging: ^15.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.10
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  flutter_gen_runner:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/fonts/Poppins/
    - assets/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900